spring:
  datasource:
    url: jdbc:postgresql://algashop-postgres:5432/billing
  flyway:
    locations: classpath:db/migration
    user: postgres
    password: postgres
    url: jdbc:postgresql://algashop-postgres:5432/billing

algashop:
  integrations:
    payment:
      fastpay:
        hostname: http://fastpay:9995